const Log = require("./logger");

const token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJNYXBDbGFpbXMiOnsiYXVkIjoiaHR0cDovLzIwLjI0NC41Ni4xNDQvZXZhbHVhdGlvbi1zZXJ2aWNlIiwiZW1haWwiOiIyMzQ4MWE0MmEzQGdlY2d1ZGxhdmFsbGVydW1pYy5pbiIsImV4cCI6MTc3ODMwODY5NSwiaWF0IjoxNzc4MzA3Nzk1LCJpc3MiOiJBZmZvcmQgTWVkaWNhbCBUZWNobm9sb2dpZXMgUHJpdmF0ZSBMaW1pdGVkIiwianRpIjoiMmI5OTkyMjAtMWEwMi00OTZhLWI2NzUtZTNmNDc3NmQxMjc1IiwibG9jYWxlIjoiZW4tSU4iLCJuYW1lIjoiZ2VldGhhc3JpIiwic3ViIjoiNTUwMGNkMTMtZTViZi00MWFmLWJhYmEtOGJhOTliMmMzZjdiIn0sImVtYWlsIjoiMjM0ODFhNDJhM0BnZWNndWRsYXZhbGxlcnVtaWMuaW4iLCJuYW1lIjoiZ2VldGhhc3JpIiwicm9sbE5vIjoiMjM0ODFhNDJhMyIsImFjY2Vzc0NvZGUiOiJlSmRDdUMiLCJjbGllbnRJRCI6IjU1MDBjZDEzLWU1YmYtNDFhZi1iYWJhLThiYTk5YjJjM2Y3YiIsImNsaWVudFNlY3JldCI6InphdFN5enBSVVNrUk15aHEifQ._aPfbpBZkSalrreI7y0OmaIE1cbZQBfFiD_9HwrP87c";

Log(
  "backend",
  "error",
  "handler",
  "test log",
  token
);